/**
 * The language review's third to fifth rounds: the mention rows of table_3 to table_6. [..] marks her; a hashtag row
 * (table_6) holds her name inside the hashtag.
 */
export const TABLE_3: [string, string][] = [
  ["May Chen", "[May] is three months old today!"],
  ["May Chen", "[May] and June on the swings."],
  ["May Chen", "Everyone waited until [May] finished her cake."],
  ["May Chen", "Aunt [May] at the picnic."],
  ["May Chen", "Little [May] on the slide."],
  ["May Chen", "Birthday girl [May] with her balloons."],
  ["May Chen", "Ben and [May], May 2021."],
  ["May Chen", "[May] turns four this May!"],
  ["May Chen", "Next to [May] is her cousin Ben."],
  ["June Carter", "Baby [June] in her crib."],
  ["June Carter", "Ben waited until [June] got home."],
  ["June Carter", "[June] Bug in her Halloween costume."],
  ["June Carter", "[June] was just two weeks old."],
  ["June Carter", "Twins April and [June] at the pool."],
  ["June Carter", "Mid June: [June] learns to ride."],
  ["April Reyes", "[April] was two months old here."],
  ["April Reyes", "[April] and May, best friends forever."],
  ["April Reyes", "Since [April] started school, mornings are chaos."],
  ["April Reyes", "Grandma rocking [April] to sleep."],
  ["August Lind", "[August] is nine months old!"],
  ["August Lind", "Until [August] arrived, the party was quiet."],
  ["August Lind", "Superhero [August] saves the day."],
  ["Will Turner", "Will it ever stop raining? [Will] in his rain boots."],
  ["Will Turner", "Captain [Will] steering the boat."],
  ["Will Turner", "[Will] you look at that smile!"],
  ["Will Turner", "Coach [Will] and the Tigers."],
  ["Hope Adams", "[Hope] the Great, conqueror of the monkey bars."],
  ["Hope Adams", "Princess [Hope] in her tiara."],
  ["Joy Okafor", "Chef [Joy] making pancakes."],
  ["Joy Okafor", "[Joy] 2 years old today!"],
  ["Grace Hopper", "Princess [Grace] at her 5th birthday party."],
  ["Grace Hopper", "Our amazing [Grace] won the spelling bee!"],
  ["Grace Hopper", "[Grace] the Brave, first day of kindergarten."],
  ["Summer Diaz", "Since [Summer] was born, the house is louder."],
  ["Summer Diaz", "Chef [Summer] making pancakes."],
  ["Summer Diaz", "[Summer] 2019 was her first beach trip."],
  ["Autumn Blake", "Until [Autumn] arrived, the party was quiet."],
  ["Autumn Blake", "[Autumn] 3rd birthday party."],
  ["Florence Adams", "[Florence], Mom and Ben at the zoo."],
  ["Florence Adams", "Nurse [Florence] with her toy stethoscope."],
  ["Paris Moreau", "[Paris], Mom and Dad at the beach."],
  ["Paris Moreau", "[Paris] 5 years old today!"],
  ["Austin Blake", "[Austin] weekend with Grandma."],
  ["Austin Blake", "Grandpa drove to [Austin], who was waiting at the gate."],
  ["Madison Clark", "[Madison] weekend with Grandma."],
  ["Madison Clark", "[Madison] 2nd birthday party!"],
  ["Jordan Price", "[Jordan], Grandpa and Leo fishing."],
  ["Jordan Price", "Coach [Jordan] and the team."],
  ["Brooklyn Shaw", "[Brooklyn], Dad and the new puppy."],
  ["Brooklyn Shaw", "[Brooklyn] trip to the dentist."],
  ["Geneva Holt", "[Geneva], Italy-bound! Packing for the trip."],
  ["Geneva Holt", "[Geneva] visit with Grandma."],
  ["Louise Dunmore", "Lake Louise with [Louise] at dawn."],
  ["Louise Dunmore", "Queen [Louise] of the sandbox."],
  ["Sierra Okafor", "Sierra Madre tee on [Sierra]."],
  ["Sierra Okafor", "Princess [Sierra] and the dragon cake."],
];

export const TABLE_4: [string, string][] = [
  ["August Lind", "[August] 6 months old today."],
  ["August Lind", "Grandma with [August], 2021."],
  ["June Carter", "[June] 1 year old!"],
  ["June Carter", "Ben tucked in [June]."],
  ["May Chen", "Leo 5 and [May] 3 at the beach."],
  ["May Chen", "Ben, Leo and [May], 2019."],
  ["May Chen", "Drawing by [May], 2019."],
  ["May Chen", "Proud of this [May]."],
  ["April Reyes", "[April] 9 months old and crawling."],
  ["April Reyes", "Grandpa and [April], 2020."],
];

export const TABLE_5: [string, string][] = [
  ["May Chen", "Leo 7, [May] 5."],
  ["May Chen", "Tucking in [May]."],
  ["May Chen", "Aunt [May] and Aunt Kay at the picnic."],
  ["May Chen", "Grandma reading to [May] in May."],
  ["May Chen", "Everyone cheered in [May]."],
  ["May Chen", "Mini-[May] and her big brother."],
  ["June Carter", "Ages this summer: Ben 9, Leo 7, [June] 4."],
  ["June Carter", "Grandpa tucks in [June]."],
  ["June Carter", "Nap time—[June] is out cold."],
  ["June Carter", "[June]-bug in her Halloween costume."],
  ["June Carter", "Up next [June]!"],
  ["June Carter", "Baby [June] with Baby Leo."],
  ["April Reyes", "Time to tuck in [April]."],
  ["April Reyes", "Cousin [April] and Grandma Ruth."],
  ["April Reyes", "Rainy April—[April] in her new boots."],
  ["August Lind", "Let's bring in [August]."],
  ["August Lind", "Hot August day—[August] in the sprinkler."],
  ["Hope Adams", "[Hope]—our little ray of sunshine—at the beach."],
  ["Hope Adams", "Big hugs for Grandma from [Hope]—she missed her!"],
  ["Grace Hopper", "Pure delight—[Grace] on her first pony ride."],
  ["Grace Hopper", "Super-[Grace] to the rescue!"],
  ["Grace Hopper", "Grace Kelly and [Grace] at the recital."],
  ["Grace Hopper", "Great-grandma Grace Kelly holding [Grace]."],
  ["Joy Okafor", "Three generations—Grandma, Mom and [Joy]."],
  ["Joy Okafor", "Birthday cake—[Joy]'s favorite!"],
  ["Will Turner", "Ready for school—[Will] and his new backpack."],
  ["Summer Diaz", "[Summer]–Ben relay race at the picnic."],
  ["Summer Diaz", "Sandcastle time—[Summer] digs in."],
  ["Autumn Blake", "Leaf pile—[Autumn] jumps right in!"],
  ["Florence Adams", "Gelato—[Florence]'s first taste."],
  ["Paris Moreau", "Beach day—[Paris] built a sandcastle."],
  ["Austin Blake", "Best buddies: Ben and [Austin]—inseparable!"],
  ["Austin Blake", "Cousin Taylor Austin with [Austin] at the lake."],
  ["Madison Clark", "[Madison]—age 4—on the swings."],
  ["Jordan Price", "Game day—[Jordan] scored twice!"],
  ["Jordan Price", "River rafting—[Jordan] at the front."],
  ["Brooklyn Shaw", "First day of school—[Brooklyn] was so brave."],
  ["Geneva Holt", "Lake day—[Geneva] at Lake Geneva."],
  ["Louise Dunmore", "Bedtime story—[Louise] asleep by page two."],
  ["Louise Dunmore", "Lake Louise—[Louise] skipping stones."],
  ["Sierra Okafor", "Mountain trip—[Sierra] on Dad's shoulders."],
  ["Sierra Okafor", "Sierra Nevada—[Sierra] at the summit."],
];

export const TABLE_6: [string, string][] = [
  ["May Chen", "#MayTheBirthdayGirl"],
  ["May Chen", "Cake says #happybirthdaymay"],
  ["May Chen", "Banner: #TeamMay"],
  ["May Chen", "Ben & [May] 2019"],
  ["May Chen", "Race results: Ben 1st, Leo 2nd, [May] 3rd!"],
  ["May Chen", "Ben came 2nd and [May] 1st!"],
  ["May Chen", "[May]🎂 turns five!"],
  ["May Chen", "🎈[May]🎈"],
  ["May Chen", "“[May],” Grandma said, “come here!”"],
  ["May Chen", "‘[May]’ in glitter on her T-shirt."],
  ["May Chen", "[May]’s first steps."],
  ["May Chen", "Grandpa with [May] (age 3)."],
  ["May Chen", "Grandpa (left) and [May] (right)."],
  ["May Chen", "[May]/Ben tag team."],
  ["May Chen", "Twins [May]/June at the pool."],
  ["June Carter", "#JuneBug on her 3rd birthday"],
  ["June Carter", "[June]-bug and Ben at the fair."],
  ["June Carter", "Dance recital: 1st place, [June]!"],
  ["June Carter", "[June] 2019 champion!"],
  ["June Carter", "Leo & [June] 2021 🌊"],
  ["April Reyes", "[April]2020 in the pool."],
  ["April Reyes", "Spelling bee: [April] 1st, Ben 2nd."],
  ["August Lind", "Birthday boy: [August] ❤️"],
  ["August Lind", "#AugustIsTwo"],
  ["Grace Hopper", "#amazinggrace at her recital"],
  ["Grace Hopper", "Ballet—#GraceTheDancer"],
  ["Hope Adams", "[Hope]’s and Ben’s kites."],
  ["Hope Adams", "“[Hope]!” — Ben, probably."],
  ["Paris Moreau", "#ParisIsFive"],
  ["Paris Moreau", "[Paris]/Ben/Leo: the three musketeers."],
  ["Madison Clark", "Team [Madison] 🏆"],
];
