/** The language review's third round (ling-r3): table_3's and table_4's mention rows. [..] marks her. */
export const TABLE_3: [string, string][] = [
  ["May Chen", "[May] is three months old today!"],
  ["May Chen", "[May] and June on the swings."],
  ["May Chen", "Everyone waited until [May] finished her cake."],
  ["May Chen", "Aunt [May] at the picnic."],
  ["May Chen", "Little [May] on the slide."],
  ["May Chen", "Birthday girl [May] with her balloons."],
  ["May Chen", "Ben and [May], May 2021."],
  ["May Chen", "[May] turns four this May!"],
  ["May Chen", "Next to [May] is her cousin Ben."],
  ["June Carter", "Baby [June] in her crib."],
  ["June Carter", "Ben waited until [June] got home."],
  ["June Carter", "[June] Bug in her Halloween costume."],
  ["June Carter", "[June] was just two weeks old."],
  ["June Carter", "Twins April and [June] at the pool."],
  ["June Carter", "Mid June: [June] learns to ride."],
  ["April Reyes", "[April] was two months old here."],
  ["April Reyes", "[April] and May, best friends forever."],
  ["April Reyes", "Since [April] started school, mornings are chaos."],
  ["April Reyes", "Grandma rocking [April] to sleep."],
  ["August Lind", "[August] is nine months old!"],
  ["August Lind", "Until [August] arrived, the party was quiet."],
  ["August Lind", "Superhero [August] saves the day."],
  ["Will Turner", "Will it ever stop raining? [Will] in his rain boots."],
  ["Will Turner", "Captain [Will] steering the boat."],
  ["Will Turner", "[Will] you look at that smile!"],
  ["Will Turner", "Coach [Will] and the Tigers."],
  ["Hope Adams", "[Hope] the Great, conqueror of the monkey bars."],
  ["Hope Adams", "Princess [Hope] in her tiara."],
  ["Joy Okafor", "Chef [Joy] making pancakes."],
  ["Joy Okafor", "[Joy] 2 years old today!"],
  ["Grace Hopper", "Princess [Grace] at her 5th birthday party."],
  ["Grace Hopper", "Our amazing [Grace] won the spelling bee!"],
  ["Grace Hopper", "[Grace] the Brave, first day of kindergarten."],
  ["Summer Diaz", "Since [Summer] was born, the house is louder."],
  ["Summer Diaz", "Chef [Summer] making pancakes."],
  ["Summer Diaz", "[Summer] 2019 was her first beach trip."],
  ["Autumn Blake", "Until [Autumn] arrived, the party was quiet."],
  ["Autumn Blake", "[Autumn] 3rd birthday party."],
  ["Florence Adams", "[Florence], Mom and Ben at the zoo."],
  ["Florence Adams", "Nurse [Florence] with her toy stethoscope."],
  ["Paris Moreau", "[Paris], Mom and Dad at the beach."],
  ["Paris Moreau", "[Paris] 5 years old today!"],
  ["Austin Blake", "[Austin] weekend with Grandma."],
  ["Austin Blake", "Grandpa drove to [Austin], who was waiting at the gate."],
  ["Madison Clark", "[Madison] weekend with Grandma."],
  ["Madison Clark", "[Madison] 2nd birthday party!"],
  ["Jordan Price", "[Jordan], Grandpa and Leo fishing."],
  ["Jordan Price", "Coach [Jordan] and the team."],
  ["Brooklyn Shaw", "[Brooklyn], Dad and the new puppy."],
  ["Brooklyn Shaw", "[Brooklyn] trip to the dentist."],
  ["Geneva Holt", "[Geneva], Italy-bound! Packing for the trip."],
  ["Geneva Holt", "[Geneva] visit with Grandma."],
  ["Louise Dunmore", "Lake Louise with [Louise] at dawn."],
  ["Louise Dunmore", "Queen [Louise] of the sandbox."],
  ["Sierra Okafor", "Sierra Madre tee on [Sierra]."],
  ["Sierra Okafor", "Princess [Sierra] and the dragon cake."],
];

export const TABLE_4: [string, string][] = [
  ["August Lind", "[August] 6 months old today."],
  ["August Lind", "Grandma with [August], 2021."],
  ["June Carter", "[June] 1 year old!"],
  ["June Carter", "Ben tucked in [June]."],
  ["May Chen", "Leo 5 and [May] 3 at the beach."],
  ["May Chen", "Ben, Leo and [May], 2019."],
  ["May Chen", "Drawing by [May], 2019."],
  ["May Chen", "Proud of this [May]."],
  ["April Reyes", "[April] 9 months old and crawling."],
  ["April Reyes", "Grandpa and [April], 2020."],
];
