-- Trips keep their zone under the tz database's own name (see canonicalTimezone in src/lib/time/local-day.ts). The
-- album's SQL reads a trip's zone in Postgres, which may be built without the legacy links (Debian's tzdata-legacy
-- split), where an old name fails every query that reads a photograph's year; and Postgres reads a bare offset like
-- '+05:00' as a POSIX zone, with its sign the other way round from the pages. The trip form used to save any name
-- a browser knew, so a trip saved before names were checked is renamed here.

-- Old names, and links, to the zone they name: every link in the tz database a browser accepts, and the zones the
-- Unicode data still calls by a name the tz database has since replaced (Europe/Kiev, Asia/Calcutta, ...).
UPDATE "Trip" t SET timezone = m.canonical FROM (VALUES
  ('Africa/Asmera', 'Africa/Asmara'),
  ('Africa/Timbuktu', 'Africa/Bamako'),
  ('America/Argentina/ComodRivadavia', 'America/Argentina/Catamarca'),
  ('America/Atka', 'America/Adak'),
  ('America/Buenos_Aires', 'America/Argentina/Buenos_Aires'),
  ('America/Catamarca', 'America/Argentina/Catamarca'),
  ('America/Cordoba', 'America/Argentina/Cordoba'),
  ('America/Ensenada', 'America/Tijuana'),
  ('America/Fort_Wayne', 'America/Indiana/Indianapolis'),
  ('America/Godthab', 'America/Nuuk'),
  ('America/Indianapolis', 'America/Indiana/Indianapolis'),
  ('America/Jujuy', 'America/Argentina/Jujuy'),
  ('America/Knox_IN', 'America/Indiana/Knox'),
  ('America/Louisville', 'America/Kentucky/Louisville'),
  ('America/Mendoza', 'America/Argentina/Mendoza'),
  ('America/Montreal', 'America/Toronto'),
  ('America/Nipigon', 'America/Toronto'),
  ('America/Pangnirtung', 'America/Iqaluit'),
  ('America/Porto_Acre', 'America/Rio_Branco'),
  ('America/Rainy_River', 'America/Winnipeg'),
  ('America/Rosario', 'America/Argentina/Cordoba'),
  ('America/Santa_Isabel', 'America/Tijuana'),
  ('America/Shiprock', 'America/Denver'),
  ('America/Thunder_Bay', 'America/Toronto'),
  ('America/Virgin', 'America/St_Thomas'),
  ('America/Yellowknife', 'America/Edmonton'),
  ('Antarctica/South_Pole', 'Antarctica/McMurdo'),
  ('Asia/Ashkhabad', 'Asia/Ashgabat'),
  ('Asia/Calcutta', 'Asia/Kolkata'),
  ('Asia/Choibalsan', 'Asia/Ulaanbaatar'),
  ('Asia/Chongqing', 'Asia/Shanghai'),
  ('Asia/Chungking', 'Asia/Shanghai'),
  ('Asia/Dacca', 'Asia/Dhaka'),
  ('Asia/Harbin', 'Asia/Shanghai'),
  ('Asia/Istanbul', 'Europe/Istanbul'),
  ('Asia/Kashgar', 'Asia/Urumqi'),
  ('Asia/Katmandu', 'Asia/Kathmandu'),
  ('Asia/Macao', 'Asia/Macau'),
  ('Asia/Rangoon', 'Asia/Yangon'),
  ('Asia/Saigon', 'Asia/Ho_Chi_Minh'),
  ('Asia/Tel_Aviv', 'Asia/Jerusalem'),
  ('Asia/Thimbu', 'Asia/Thimphu'),
  ('Asia/Ujung_Pandang', 'Asia/Makassar'),
  ('Asia/Ulan_Bator', 'Asia/Ulaanbaatar'),
  ('Atlantic/Faeroe', 'Atlantic/Faroe'),
  ('Atlantic/Jan_Mayen', 'Arctic/Longyearbyen'),
  ('Australia/ACT', 'Australia/Sydney'),
  ('Australia/Canberra', 'Australia/Sydney'),
  ('Australia/Currie', 'Australia/Hobart'),
  ('Australia/LHI', 'Australia/Lord_Howe'),
  ('Australia/NSW', 'Australia/Sydney'),
  ('Australia/North', 'Australia/Darwin'),
  ('Australia/Queensland', 'Australia/Brisbane'),
  ('Australia/South', 'Australia/Adelaide'),
  ('Australia/Tasmania', 'Australia/Hobart'),
  ('Australia/Victoria', 'Australia/Melbourne'),
  ('Australia/West', 'Australia/Perth'),
  ('Australia/Yancowinna', 'Australia/Broken_Hill'),
  ('Brazil/Acre', 'America/Rio_Branco'),
  ('Brazil/DeNoronha', 'America/Noronha'),
  ('Brazil/East', 'America/Sao_Paulo'),
  ('Brazil/West', 'America/Manaus'),
  ('Canada/Atlantic', 'America/Halifax'),
  ('Canada/Central', 'America/Winnipeg'),
  ('Canada/Eastern', 'America/Toronto'),
  ('Canada/Mountain', 'America/Edmonton'),
  ('Canada/Newfoundland', 'America/St_Johns'),
  ('Canada/Pacific', 'America/Vancouver'),
  ('Canada/Saskatchewan', 'America/Regina'),
  ('Canada/Yukon', 'America/Whitehorse'),
  ('Chile/Continental', 'America/Santiago'),
  ('Chile/EasterIsland', 'Pacific/Easter'),
  ('Cuba', 'America/Havana'),
  ('Egypt', 'Africa/Cairo'),
  ('Eire', 'Europe/Dublin'),
  ('Etc/GMT+0', 'UTC'),
  ('Etc/GMT-0', 'UTC'),
  ('Etc/GMT0', 'UTC'),
  ('Etc/Greenwich', 'UTC'),
  ('Etc/UCT', 'UTC'),
  ('Etc/Universal', 'UTC'),
  ('Etc/Zulu', 'UTC'),
  ('Europe/Belfast', 'Europe/London'),
  ('Europe/Kiev', 'Europe/Kyiv'),
  ('Europe/Nicosia', 'Asia/Nicosia'),
  ('Europe/Tiraspol', 'Europe/Chisinau'),
  ('Europe/Uzhgorod', 'Europe/Kyiv'),
  ('Europe/Zaporozhye', 'Europe/Kyiv'),
  ('GB', 'Europe/London'),
  ('GB-Eire', 'Europe/London'),
  ('GMT', 'UTC'),
  ('GMT+0', 'UTC'),
  ('GMT-0', 'UTC'),
  ('GMT0', 'UTC'),
  ('Greenwich', 'UTC'),
  ('Hongkong', 'Asia/Hong_Kong'),
  ('Iceland', 'Atlantic/Reykjavik'),
  ('Iran', 'Asia/Tehran'),
  ('Israel', 'Asia/Jerusalem'),
  ('Jamaica', 'America/Jamaica'),
  ('Japan', 'Asia/Tokyo'),
  ('Kwajalein', 'Pacific/Kwajalein'),
  ('Libya', 'Africa/Tripoli'),
  ('Mexico/BajaNorte', 'America/Tijuana'),
  ('Mexico/BajaSur', 'America/Mazatlan'),
  ('Mexico/General', 'America/Mexico_City'),
  ('NZ', 'Pacific/Auckland'),
  ('NZ-CHAT', 'Pacific/Chatham'),
  ('Navajo', 'America/Denver'),
  ('PRC', 'Asia/Shanghai'),
  ('Pacific/Enderbury', 'Pacific/Kanton'),
  ('Pacific/Johnston', 'Pacific/Honolulu'),
  ('Pacific/Ponape', 'Pacific/Pohnpei'),
  ('Pacific/Samoa', 'Pacific/Pago_Pago'),
  ('Pacific/Truk', 'Pacific/Chuuk'),
  ('Pacific/Yap', 'Pacific/Chuuk'),
  ('Poland', 'Europe/Warsaw'),
  ('Portugal', 'Europe/Lisbon'),
  ('ROC', 'Asia/Taipei'),
  ('ROK', 'Asia/Seoul'),
  ('Singapore', 'Asia/Singapore'),
  ('Turkey', 'Europe/Istanbul'),
  ('UCT', 'UTC'),
  ('US/Alaska', 'America/Anchorage'),
  ('US/Aleutian', 'America/Adak'),
  ('US/Arizona', 'America/Phoenix'),
  ('US/Central', 'America/Chicago'),
  ('US/East-Indiana', 'America/Indiana/Indianapolis'),
  ('US/Eastern', 'America/New_York'),
  ('US/Hawaii', 'Pacific/Honolulu'),
  ('US/Indiana-Starke', 'America/Indiana/Knox'),
  ('US/Michigan', 'America/Detroit'),
  ('US/Mountain', 'America/Denver'),
  ('US/Pacific', 'America/Los_Angeles'),
  ('US/Samoa', 'Pacific/Pago_Pago'),
  ('Universal', 'UTC'),
  ('W-SU', 'Europe/Moscow'),
  ('Zulu', 'UTC')
) AS m(legacy, canonical) WHERE t.timezone = m.legacy;

-- A bare offset ('+05:00', '+0500', '+05'): the fixed-offset zone that says the same, whose sign runs the POSIX way
-- ('+05:00' is Etc/GMT-5), or UTC where there is none (a half-hour offset, or one past the tz database's range).
UPDATE "Trip" t SET timezone = CASE
    WHEN o.m[2]::int = 0 OR coalesce(o.m[3], '00') <> '00' THEN 'UTC'
    WHEN o.m[1] = '+' AND o.m[2]::int <= 14 THEN 'Etc/GMT-' || o.m[2]::int
    WHEN o.m[1] = '-' AND o.m[2]::int <= 12 THEN 'Etc/GMT+' || o.m[2]::int
    ELSE 'UTC'
  END
FROM (SELECT id, regexp_match(timezone, '^([+-])(\d{2}):?(\d{2})?$') AS m FROM "Trip") o
WHERE o.id = t.id AND o.m IS NOT NULL;
